package M6.UF2.Activitat5.entity;
// Generated 06-feb-2021 17:17:20 by Hibernate Tools 4.3.1



/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private Integer idMovimiento;
     private Partida partida;
     private int columnaOrigen;
     private int columna;
     private int filaOrigen;
     private int fila;

    public Movimiento() {
    }

    public Movimiento(Partida partida, int columnaOrigen, int columna, int filaOrigen, int fila) {
       this.partida = partida;
       this.columnaOrigen = columnaOrigen;
       this.columna = columna;
       this.filaOrigen = filaOrigen;
       this.fila = fila;
    }
   
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getColumnaOrigen() {
        return this.columnaOrigen;
    }
    
    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }
    public int getFilaOrigen() {
        return this.filaOrigen;
    }
    
    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }




}


