package M6.UF2.Activitat5.entity;
// Generated 30-ene-2021 17:44:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "movimiento")
public class Movimiento  implements java.io.Serializable {

    @Id @GeneratedValue
    @Column(name = "idMovimiento")
     private int idMovimiento;
    @Column(name = "idPartida")
     private int idPartida;
     @Column(name = "columnaOrigen")
     private int columnaOrigen;
     @Column(name = "columna")
     private int columna;
     @Column(name = "filaOrigen")
     private int filaOrigen;
     @Column(name = "fila")
     private int fila;
     

    public Movimiento() {
    }

    public Movimiento(int idMovimiento, int idPartida, int columnaOrigen, int columna, int filaOrigen, int fila) {
       this.idMovimiento = idMovimiento;
       this.idPartida = idPartida;
       this.columnaOrigen = columnaOrigen;
       this.columna = columna;
       this.filaOrigen = filaOrigen;
       this.fila = fila;
    }
   
    public int getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(int idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public int getColumnaOrigen() {
        return this.columnaOrigen;
    }
    
    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }
    public int getFilaOrigen() {
        return this.filaOrigen;
    }
    
    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }




}


