package M6.UF2.Activitat5.entity;
// Generated 30-ene-2021 17:44:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name = "movimiento")
public class Movimiento  implements java.io.Serializable {

    @Id @GeneratedValue
    @Column(name = "idMovimiento")
     private Integer idMovimiento;
    @Column(name = "idPartida")
     private Partida partida;
     @Column(name = "columnaOrigen")
     private int columnaOrigen;
     @Column(name = "columna")
     private int columna;
     @Column(name = "filaOrigen")
     private int filaOrigen;
     @Column(name = "fila")
     private int fila;
     

    public Movimiento() {
    }

    public Movimiento(Partida partida, int columnaOrigen, int columna, int filaOrigen, int fila) {
       this.partida = partida;
       this.columnaOrigen = columnaOrigen;
       this.columna = columna;
       this.filaOrigen = filaOrigen;
       this.fila = fila;
    }
   
    public int getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getColumnaOrigen() {
        return this.columnaOrigen;
    }
    
    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }
    public int getFilaOrigen() {
        return this.filaOrigen;
    }
    
    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }




}


