package M6.UF2.Activitat5.entity;
// Generated 30-ene-2021 17:44:43 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "partida")
public class Partida  implements java.io.Serializable {

    @Id @GeneratedValue
    @Column(name = "id")
     private Integer id;
    @Column(name = "data")
     private Date data;
    @Column(name = "guanyador")
     private String guanyador;

    public Partida() {
    }

    public Partida(String guanyador) {
        this.guanyador = guanyador;
    }
 
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(String guanyador) {
        this.guanyador = guanyador;
    }




}


