package M6.UF2.Activitat5.entity;
// Generated 06-feb-2021 17:17:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer idPartida;
     private String guanyador;
     private Set movimientos = new HashSet(0);

    public Partida() {
    }

	
    public Partida(String guanyador) {
        this.guanyador = guanyador;
    }
    public Partida(String guanyador, Set movimientos) {
       this.guanyador = guanyador;
       this.movimientos = movimientos;
    }
   
    public Integer getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }
    public String getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(String guanyador) {
        this.guanyador = guanyador;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


