/*
Game of The Year
 */
package M3.UF6.Activitat8;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author alexp
 */
public class GameOfTheYear extends javax.swing.JFrame {
    
    int contador = 0;
    String stringtaula[][] = new String[4][4];
    int fi, per2;
    /**
     * Creates new form GameOfTheYear
     */
    public GameOfTheYear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTaula = new javax.swing.JTable();
        jTextFieldPunts = new javax.swing.JTextField();
        jButtonSortir = new javax.swing.JButton();
        jButtonInici = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelRecord = new javax.swing.JLabel();
        jTextFieldRecord = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTaula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTaula.setPreferredSize(new java.awt.Dimension(300, 300));
        jTaula.setRowHeight(70);
        jTaula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTaula);

        jTextFieldPunts.setEditable(false);

        jButtonSortir.setText("Sortir");
        jButtonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortirActionPerformed(evt);
            }
        });

        jButtonInici.setText("Començar");
        jButtonInici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciActionPerformed(evt);
            }
        });

        jLabel1.setText("Punts:");

        jLabelRecord.setText("Record:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSortir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonInici))
                        .addComponent(jTextFieldPunts))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRecord)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRecord)
                            .addComponent(jTextFieldRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPunts, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSortir)
                            .addComponent(jButtonInici))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boto per tancar el joc i veure quans punts has conseguit
    private void jButtonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortirActionPerformed
        JOptionPane.showConfirmDialog(null, "Has fet " + contador, "Window", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButtonSortirActionPerformed

    //Boto per començar i reiniciar el joc
    private void jButtonIniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciActionPerformed
        if(jButtonInici.getText().equalsIgnoreCase("Començar")){
            reiniciaGame();
            reiniciataula();
            jButtonInici.setText("Reinicia pantalla");
        }else{
            jButtonInici.setText("Començar");
            reiniciaGame();
            reiniciataula();
        }
                
    }//GEN-LAST:event_jButtonIniciActionPerformed
    
    //Clicar a la taula
    private void jTaulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaulaMouseClicked
        
    }//GEN-LAST:event_jTaulaMouseClicked
    //Omple la taula amb X W 0 per que funcioni el joc
    private void reiniciaGame(){
        Random random = new Random();
        int rdm;
        
        for (int i=0; i<4; i++){
            for (int j=0; j<4; j++){
                rdm = random.nextInt(3);
                if(rdm == 0){
                    //caselles am 0
                   stringtaula[i][j] = "0"; 
                }else if(rdm == 1){
                    //caselles amb X
                    if (fi != 2) {
                        stringtaula[i][j] = "X";
                        fi++;
                    }else{
                        stringtaula[i][j] = "0";
                    }
                    }else{
                    //caselles amb W
                    if(per2 != 3){
                        stringtaula[i][j] = "W";
                    }else{
                        stringtaula[i][j] = "0";
                    }
                }
            }
        }
    }
    //Omple la taula amb ?
    private void reiniciataula(){
        for (int i=0; i<4; i++){
            for (int j=0; j<4; j++){
                jTaula.setValueAt("?", i, j);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOfTheYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOfTheYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInici;
    private javax.swing.JButton jButtonSortir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTaula;
    private javax.swing.JTextField jTextFieldPunts;
    private javax.swing.JTextField jTextFieldRecord;
    // End of variables declaration//GEN-END:variables
}
